CREATE TABLE `accessManagement` (
  `id` int NOT NULL AUTO_INCREMENT,
  `empId` int NOT NULL,
  `projectRead` varchar(50) NOT NULL,
  `projectAction` varchar(50) NOT NULL,
  `clientRead` varchar(50) NOT NULL,
  `clientAction` varchar(50) NOT NULL,
  `employeeRead` varchar(50) NOT NULL,
  `employeeAction` varchar(50) NOT NULL,
  `payrollItemRead` varchar(50) NOT NULL,
  `payrollItemAction` varchar(50) NOT NULL,
  `accessRead` varchar(50) NOT NULL,
  `accessAction` varchar(50) NOT NULL,
  `invoiceRead` varchar(50) NOT NULL,
  `invoiceAction` varchar(50) NOT NULL,
  `dashboardRead` varchar(50) NOT NULL,
  `taskRead` varchar(50) NOT NULL,
  `taskAction` varchar(50) NOT NULL,
  `holidaysRead` varchar(50) NOT NULL,
  `leavesRead` varchar(50) NOT NULL,
  `leavesAction` varchar(50) NOT NULL,
  `departmentsRead` varchar(50) NOT NULL,
  `departmentsAction` varchar(50) NOT NULL,
  `designationRead` varchar(50) NOT NULL,
  `designationAction` varchar(50) NOT NULL,
  `salaryRead` varchar(50) NOT NULL,
  `salaryAction` varchar(50) NOT NULL,
  `holidaysAction` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) --=61 
